# Usando a imagem oficial do MySQL (versão mais leve)
FROM mysql:8.0-oracle
# Variáveis de ambiente para configurar o banco
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=meubanco
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=senha
# Expor a porta padrão do MySQL
EXPOSE 3306